// AUTO-GENERATED by scripts/sync-v3-catalog.mjs from Origami's v3 OpenAPI spec
// (https://docs.origami.chat/openapi-v3.yaml, info.version "3.0"). Do not hand-edit:
// run `pnpm sync:v3` to regenerate.

import type { V3Operation } from "./types.js";

export const V3_SPEC_VERSION = "3.0";

export const V3_OPERATIONS: V3Operation[] = [
  {
    "id": "jobs.list",
    "method": "GET",
    "path": "/jobs",
    "summary": "List the caller's visible Jobs, newest first",
    "tag": "jobs",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "status",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "queued",
          "running",
          "needs_input",
          "succeeded",
          "failed",
          "cancelled"
        ]
      },
      {
        "name": "operation",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "target_type",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "list",
          "search",
          "campaign",
          "chat",
          "domain_order"
        ]
      },
      {
        "name": "target_id",
        "in": "query",
        "required": false,
        "kind": "string"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/jobs-list"
  },
  {
    "id": "jobs.get",
    "method": "GET",
    "path": "/jobs/{job_id}",
    "summary": "Read one job. Honor next_poll_at when you poll.",
    "tag": "jobs",
    "params": [
      {
        "name": "job_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/jobs-get"
  },
  {
    "id": "jobs.cancel",
    "method": "POST",
    "path": "/jobs/{job_id}/cancel",
    "summary": "Request cooperative cancel of a Job",
    "tag": "jobs",
    "params": [
      {
        "name": "job_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/jobs-cancel"
  },
  {
    "id": "jobs.input",
    "method": "POST",
    "path": "/jobs/{job_id}/input",
    "summary": "Answer a needs_input Job's questions and resume it",
    "tag": "jobs",
    "params": [
      {
        "name": "job_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "answers",
        "required": true,
        "kind": "list"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/jobs-input"
  },
  {
    "id": "account.get",
    "method": "GET",
    "path": "/account",
    "summary": "Read the org, including plan, capability flags, concurrent agent runs, and project counts.",
    "tag": "account",
    "params": [],
    "docs": "https://docs.origami.chat/v3/reference/account-get"
  },
  {
    "id": "account.credits.get",
    "method": "GET",
    "path": "/account/credits",
    "summary": "Read the reservation-aware wallet balance in credits",
    "tag": "account",
    "params": [],
    "docs": "https://docs.origami.chat/v3/reference/account-credits-get"
  },
  {
    "id": "account.credits.usage",
    "method": "GET",
    "path": "/account/credits/usage",
    "summary": "Credits spent in a month, with a per-section breakdown",
    "tag": "account",
    "params": [
      {
        "name": "period",
        "in": "query",
        "required": false,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-credits-usage"
  },
  {
    "id": "account.rate_limits.get",
    "method": "GET",
    "path": "/account/rate-limits",
    "summary": "Current rate-limit buckets, with limit, remaining, and reset per bucket.",
    "tag": "account",
    "params": [],
    "docs": "https://docs.origami.chat/v3/reference/account-rate-limits-get"
  },
  {
    "id": "account.projects.list",
    "method": "GET",
    "path": "/account/projects",
    "summary": "List projects under the parent org",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-projects-list"
  },
  {
    "id": "account.projects.create",
    "method": "POST",
    "path": "/account/projects",
    "summary": "Create a project (optional monthly credit cap)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "name",
        "required": true,
        "kind": "string"
      },
      {
        "name": "monthly_credit_cap",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "enforcement",
        "required": false,
        "kind": "string",
        "enum": [
          "hard",
          "soft"
        ]
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-projects-create"
  },
  {
    "id": "account.projects.get",
    "method": "GET",
    "path": "/account/projects/{project_id}",
    "summary": "Read one project",
    "tag": "account",
    "params": [
      {
        "name": "project_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-projects-get"
  },
  {
    "id": "account.projects.patch",
    "method": "PATCH",
    "path": "/account/projects/{project_id}",
    "summary": "Rename a project or change its budget cap / enforcement",
    "tag": "account",
    "params": [
      {
        "name": "project_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "monthly_credit_cap",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "enforcement",
        "required": false,
        "kind": "string",
        "enum": [
          "hard",
          "soft"
        ]
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-projects-patch"
  },
  {
    "id": "account.projects.delete",
    "method": "DELETE",
    "path": "/account/projects/{project_id}",
    "summary": "Delete a project (previews lists/rows/chats/campaigns without confirm)",
    "tag": "account",
    "params": [
      {
        "name": "project_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-projects-delete"
  },
  {
    "id": "account.chats.list",
    "method": "GET",
    "path": "/account/chats",
    "summary": "List chats (onboarding/content/scheduled excluded by default)",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "kind",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "chat",
          "content"
        ]
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-chats-list"
  },
  {
    "id": "account.chats.create",
    "method": "POST",
    "path": "/account/chats",
    "summary": "Create an empty chat",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "name",
        "required": false,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-chats-create"
  },
  {
    "id": "account.chats.get",
    "method": "GET",
    "path": "/account/chats/{chat_id}",
    "summary": "Read one chat with linked list/campaign summaries",
    "tag": "account",
    "params": [
      {
        "name": "chat_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-chats-get"
  },
  {
    "id": "account.chats.patch",
    "method": "PATCH",
    "path": "/account/chats/{chat_id}",
    "summary": "Rename a chat",
    "tag": "account",
    "params": [
      {
        "name": "chat_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "name",
        "required": true,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-chats-patch"
  },
  {
    "id": "account.chats.archive",
    "method": "DELETE",
    "path": "/account/chats/{chat_id}",
    "summary": "Archive a chat (soft-delete; no confirm required)",
    "tag": "account",
    "params": [
      {
        "name": "chat_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-chats-archive"
  },
  {
    "id": "account.chats.links.create",
    "method": "POST",
    "path": "/account/chats/{chat_id}/links",
    "summary": "Link an existing list or campaign to a chat (idempotent)",
    "tag": "account",
    "params": [
      {
        "name": "chat_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "list_id",
        "required": false,
        "kind": "string"
      },
      {
        "name": "campaign_id",
        "required": false,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-chats-links-create"
  },
  {
    "id": "account.chats.links.delete",
    "method": "DELETE",
    "path": "/account/chats/{chat_id}/links/{slug}",
    "summary": "Unlink a list or campaign from a chat (does not delete it)",
    "tag": "account",
    "params": [
      {
        "name": "chat_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "slug",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-chats-links-delete"
  },
  {
    "id": "account.chats.messages.create",
    "method": "POST",
    "path": "/account/chats/{chat_id}/messages",
    "summary": "Send a chat message and run the agent (returns a Job)",
    "tag": "account",
    "params": [
      {
        "name": "chat_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "prompt",
        "required": true,
        "kind": "string"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/account-chats-messages-create"
  },
  {
    "id": "account.senders.list",
    "method": "GET",
    "path": "/account/senders",
    "summary": "List the org's email and LinkedIn senders",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "channel",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "email",
          "linkedin"
        ]
      },
      {
        "name": "status",
        "in": "query",
        "required": false,
        "kind": "string"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-senders-list"
  },
  {
    "id": "account.senders.get",
    "method": "GET",
    "path": "/account/senders/{sender_id}",
    "summary": "Read one sender (secrets never returned)",
    "tag": "account",
    "params": [
      {
        "name": "sender_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-senders-get"
  },
  {
    "id": "account.senders.patch",
    "method": "PATCH",
    "path": "/account/senders/{sender_id}",
    "summary": "Update safe sender settings (no credentials)",
    "tag": "account",
    "params": [
      {
        "name": "sender_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "display_name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "signature_html",
        "required": false,
        "kind": "string"
      },
      {
        "name": "send_as_email",
        "required": false,
        "kind": "string"
      },
      {
        "name": "daily_limit",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "timezone",
        "required": false,
        "kind": "string"
      },
      {
        "name": "base_gap_minutes",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "random_gap_minutes",
        "required": false,
        "kind": "integer"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-senders-patch"
  },
  {
    "id": "account.senders.delete",
    "method": "DELETE",
    "path": "/account/senders/{sender_id}",
    "summary": "Disconnect a sender (previews stops when sends are scheduled)",
    "tag": "account",
    "params": [
      {
        "name": "sender_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-senders-delete"
  },
  {
    "id": "account.senders.warmup.enable",
    "method": "POST",
    "path": "/account/senders/{sender_id}/warmup/enable",
    "summary": "Enable warmup for an email sender (feature-gated)",
    "tag": "account",
    "params": [
      {
        "name": "sender_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-senders-warmup-enable"
  },
  {
    "id": "account.senders.warmup.disable",
    "method": "POST",
    "path": "/account/senders/{sender_id}/warmup/disable",
    "summary": "Disable warmup for an email sender",
    "tag": "account",
    "params": [
      {
        "name": "sender_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-senders-warmup-disable"
  },
  {
    "id": "account.senders.imap.create",
    "method": "POST",
    "path": "/account/senders/imap",
    "summary": "Connect a native SMTP/IMAP mailbox (write-only credentials)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "email",
        "required": true,
        "kind": "string"
      },
      {
        "name": "first_name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "last_name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "timezone",
        "required": false,
        "kind": "string"
      },
      {
        "name": "smtp_host",
        "required": true,
        "kind": "string"
      },
      {
        "name": "smtp_port",
        "required": true,
        "kind": "integer"
      },
      {
        "name": "smtp_username",
        "required": true,
        "kind": "string"
      },
      {
        "name": "smtp_password",
        "required": true,
        "kind": "string"
      },
      {
        "name": "imap_host",
        "required": true,
        "kind": "string"
      },
      {
        "name": "imap_port",
        "required": true,
        "kind": "integer"
      },
      {
        "name": "imap_username",
        "required": true,
        "kind": "string"
      },
      {
        "name": "imap_password",
        "required": true,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-senders-imap-create"
  },
  {
    "id": "account.senders.connect",
    "method": "POST",
    "path": "/account/senders/connect",
    "summary": "Get a connect-accounts handoff URL (OAuth never completes in-process)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "channel",
        "required": true,
        "kind": "string",
        "enum": [
          "email",
          "linkedin"
        ]
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-senders-connect"
  },
  {
    "id": "account.senders.reconnect",
    "method": "POST",
    "path": "/account/senders/{sender_id}/reconnect",
    "summary": "Reconnect a needs_reauth sender (handoff, or IMAP re-submit instruction)",
    "tag": "account",
    "params": [
      {
        "name": "sender_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-senders-reconnect"
  },
  {
    "id": "account.senders.send_as_aliases.list",
    "method": "GET",
    "path": "/account/senders/{sender_id}/send-as-aliases",
    "summary": "List verified send-as aliases (empty for IMAP/LinkedIn senders)",
    "tag": "account",
    "params": [
      {
        "name": "sender_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-senders-send-as-aliases-list"
  },
  {
    "id": "account.domains.search",
    "method": "POST",
    "path": "/account/domains/search",
    "summary": "Search available domains with prices (never charges)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "query",
        "required": true,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-domains-search"
  },
  {
    "id": "account.domains.list",
    "method": "GET",
    "path": "/account/domains",
    "summary": "List owned DFY domains",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-domains-list"
  },
  {
    "id": "account.domains.get",
    "method": "GET",
    "path": "/account/domains/{domain_id}",
    "summary": "Read one owned domain",
    "tag": "account",
    "params": [
      {
        "name": "domain_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-domains-get"
  },
  {
    "id": "account.domains.purchase",
    "method": "POST",
    "path": "/account/domains/purchase",
    "summary": "Purchase domains on the card on file (priced preview without confirm)",
    "tag": "account",
    "params": [
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "body": [
      {
        "name": "domains",
        "required": true,
        "kind": "list"
      },
      {
        "name": "forwarding_domain",
        "required": false,
        "kind": "string"
      },
      {
        "name": "timezone",
        "required": false,
        "kind": "string"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/account-domains-purchase"
  },
  {
    "id": "account.domains.renewal.cancel",
    "method": "POST",
    "path": "/account/domains/{domain_id}/renewal/cancel",
    "summary": "Cancel auto-renewal for a domain",
    "tag": "account",
    "params": [
      {
        "name": "domain_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-domains-renewal-cancel"
  },
  {
    "id": "account.domains.renewal.undo",
    "method": "POST",
    "path": "/account/domains/{domain_id}/renewal/undo",
    "summary": "Undo a renewal cancellation",
    "tag": "account",
    "params": [
      {
        "name": "domain_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-domains-renewal-undo"
  },
  {
    "id": "account.domains.forwarding.set",
    "method": "POST",
    "path": "/account/domains/{domain_id}/forwarding",
    "summary": "Set apex forwarding for an owned domain",
    "tag": "account",
    "params": [
      {
        "name": "domain_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "forwarding_domain",
        "required": true,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-domains-forwarding-set"
  },
  {
    "id": "account.mailboxes.list",
    "method": "GET",
    "path": "/account/mailboxes",
    "summary": "List DFY mailboxes (no passwords)",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-mailboxes-list"
  },
  {
    "id": "account.mailboxes.provision",
    "method": "POST",
    "path": "/account/mailboxes",
    "summary": "Provision mailboxes on owned domains (always async)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "mailboxes",
        "required": true,
        "kind": "json"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/account-mailboxes-provision"
  },
  {
    "id": "account.exclusion_lists.get",
    "method": "GET",
    "path": "/account/exclusion-lists",
    "summary": "Read the effective exclusion-list source and entry counts",
    "tag": "account",
    "params": [],
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-get"
  },
  {
    "id": "account.exclusion_lists.patch",
    "method": "PATCH",
    "path": "/account/exclusion-lists",
    "summary": "Switch a project between the shared org list and its private list",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "source",
        "required": true,
        "kind": "string",
        "enum": [
          "organization",
          "project"
        ]
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-patch"
  },
  {
    "id": "account.exclusion_lists.people.list",
    "method": "GET",
    "path": "/account/exclusion-lists/people",
    "summary": "List people exclusion entries, filterable by identifier",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "email",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "linkedin_slug",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "company_domain",
        "in": "query",
        "required": false,
        "kind": "string"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-people-list"
  },
  {
    "id": "account.exclusion_lists.people.add",
    "method": "POST",
    "path": "/account/exclusion-lists/people",
    "summary": "Add people entries (single or bulk ≤1,000; idempotent upsert)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "linkedin_slug",
        "required": false,
        "kind": "string"
      },
      {
        "name": "full_name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "email",
        "required": false,
        "kind": "string"
      },
      {
        "name": "company_domain",
        "required": false,
        "kind": "string"
      },
      {
        "name": "company_name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "entries",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-people-add"
  },
  {
    "id": "account.exclusion_lists.people.clear",
    "method": "DELETE",
    "path": "/account/exclusion-lists/people",
    "summary": "Clear the people exclusion list",
    "tag": "account",
    "params": [
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-people-clear"
  },
  {
    "id": "account.exclusion_lists.people.delete",
    "method": "DELETE",
    "path": "/account/exclusion-lists/people/{entry_id}",
    "summary": "Remove one people exclusion entry",
    "tag": "account",
    "params": [
      {
        "name": "entry_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-people-delete"
  },
  {
    "id": "account.exclusion_lists.companies.list",
    "method": "GET",
    "path": "/account/exclusion-lists/companies",
    "summary": "List company exclusion entries, filterable by identifier",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "company_domain",
        "in": "query",
        "required": false,
        "kind": "string"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-companies-list"
  },
  {
    "id": "account.exclusion_lists.companies.add",
    "method": "POST",
    "path": "/account/exclusion-lists/companies",
    "summary": "Add company entries (single or bulk ≤1,000; idempotent upsert)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "company_domain",
        "required": false,
        "kind": "string"
      },
      {
        "name": "company_name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "entries",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-companies-add"
  },
  {
    "id": "account.exclusion_lists.companies.clear",
    "method": "DELETE",
    "path": "/account/exclusion-lists/companies",
    "summary": "Clear the company exclusion list",
    "tag": "account",
    "params": [
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-companies-clear"
  },
  {
    "id": "account.exclusion_lists.companies.delete",
    "method": "DELETE",
    "path": "/account/exclusion-lists/companies/{entry_id}",
    "summary": "Remove one company exclusion entry",
    "tag": "account",
    "params": [
      {
        "name": "entry_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-exclusion-lists-companies-delete"
  },
  {
    "id": "account.webhooks.list",
    "method": "GET",
    "path": "/account/webhooks",
    "summary": "List webhook endpoints",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-webhooks-list"
  },
  {
    "id": "account.webhooks.create",
    "method": "POST",
    "path": "/account/webhooks",
    "summary": "Create a webhook endpoint (secret shown once)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "url",
        "required": true,
        "kind": "string"
      },
      {
        "name": "event_types",
        "required": true,
        "kind": "list"
      },
      {
        "name": "name",
        "required": false,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-webhooks-create"
  },
  {
    "id": "account.webhooks.get",
    "method": "GET",
    "path": "/account/webhooks/{webhook_id}",
    "summary": "Read one webhook endpoint",
    "tag": "account",
    "params": [
      {
        "name": "webhook_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-webhooks-get"
  },
  {
    "id": "account.webhooks.patch",
    "method": "PATCH",
    "path": "/account/webhooks/{webhook_id}",
    "summary": "Update a webhook endpoint's url, events, or enabled state",
    "tag": "account",
    "params": [
      {
        "name": "webhook_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "url",
        "required": false,
        "kind": "string"
      },
      {
        "name": "event_types",
        "required": false,
        "kind": "list"
      },
      {
        "name": "name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "enabled",
        "required": false,
        "kind": "boolean"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-webhooks-patch"
  },
  {
    "id": "account.webhooks.delete",
    "method": "DELETE",
    "path": "/account/webhooks/{webhook_id}",
    "summary": "Delete a webhook endpoint",
    "tag": "account",
    "params": [
      {
        "name": "webhook_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-webhooks-delete"
  },
  {
    "id": "account.webhooks.rotate",
    "method": "POST",
    "path": "/account/webhooks/{webhook_id}/rotate",
    "summary": "Rotate an endpoint's signing secret (new secret shown once)",
    "tag": "account",
    "params": [
      {
        "name": "webhook_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-webhooks-rotate"
  },
  {
    "id": "account.webhooks.test",
    "method": "POST",
    "path": "/account/webhooks/{webhook_id}/test",
    "summary": "Send a webhook.test event to an endpoint",
    "tag": "account",
    "params": [
      {
        "name": "webhook_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-webhooks-test"
  },
  {
    "id": "account.keys.list",
    "method": "GET",
    "path": "/account/keys",
    "summary": "List API keys (names, suffix, role — never secrets)",
    "tag": "account",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/account-keys-list"
  },
  {
    "id": "account.keys.create",
    "method": "POST",
    "path": "/account/keys",
    "summary": "Create an API key (secret shown once; role ≤ creator's role)",
    "tag": "account",
    "params": [],
    "body": [
      {
        "name": "name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "role",
        "required": false,
        "kind": "string",
        "enum": [
          "admin",
          "member"
        ]
      },
      {
        "name": "project_id",
        "required": false,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/account-keys-create"
  },
  {
    "id": "account.keys.revoke",
    "method": "DELETE",
    "path": "/account/keys/{key_id}",
    "summary": "Revoke an API key",
    "tag": "account",
    "params": [
      {
        "name": "key_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/account-keys-revoke"
  },
  {
    "id": "leads.lists.list",
    "method": "GET",
    "path": "/leads/lists",
    "summary": "List lead lists (exact case-insensitive name filter)",
    "tag": "leads",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "name",
        "in": "query",
        "required": false,
        "kind": "string"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-list"
  },
  {
    "id": "leads.lists.create",
    "method": "POST",
    "path": "/leads/lists",
    "summary": "Create an empty list (no search, no rows, no agent)",
    "tag": "leads",
    "params": [],
    "body": [
      {
        "name": "name",
        "required": true,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-create"
  },
  {
    "id": "leads.lists.get",
    "method": "GET",
    "path": "/leads/lists/{list_id}",
    "summary": "Read one list with columns and searches",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-get"
  },
  {
    "id": "leads.lists.patch",
    "method": "PATCH",
    "path": "/leads/lists/{list_id}",
    "summary": "Rename a list",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "name",
        "required": true,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-patch"
  },
  {
    "id": "leads.lists.delete",
    "method": "DELETE",
    "path": "/leads/lists/{list_id}",
    "summary": "Delete a list (previews without confirm; cancels its active Jobs)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-delete"
  },
  {
    "id": "leads.lists.stats.get",
    "method": "GET",
    "path": "/leads/lists/{list_id}/stats",
    "summary": "Read the list's sourcing/qualification funnel and credit economics",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-stats-get"
  },
  {
    "id": "leads.lists.fetch",
    "method": "POST",
    "path": "/leads/lists/{list_id}/fetch",
    "summary": "Fetch leads into this list from a brief (AGENT; compact list context)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "brief",
        "required": true,
        "kind": "string"
      },
      {
        "name": "count",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "quality",
        "required": false,
        "kind": "string",
        "enum": [
          "fast",
          "accurate"
        ]
      },
      {
        "name": "exclude_list_ids",
        "required": false,
        "kind": "list"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-fetch"
  },
  {
    "id": "leads.lists.fetch_more",
    "method": "POST",
    "path": "/leads/lists/{list_id}/fetch-more",
    "summary": "Fetch more from the list's single active search (alias of searches fetch-more)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "count",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "exclude_list_ids",
        "required": false,
        "kind": "list"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-fetch-more"
  },
  {
    "id": "leads.lists.enrich",
    "method": "POST",
    "path": "/leads/lists/{list_id}/enrich",
    "summary": "Enrich named code columns (or all auto-trigger columns)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "column_slugs",
        "required": false,
        "kind": "list"
      },
      {
        "name": "row_ids",
        "required": false,
        "kind": "list"
      },
      {
        "name": "reenrich",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-enrich"
  },
  {
    "id": "leads.lists.enrich_custom",
    "method": "POST",
    "path": "/leads/lists/{list_id}/enrich_custom",
    "summary": "Add or fill a column from instructions (AGENT)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "instructions",
        "required": true,
        "kind": "string"
      },
      {
        "name": "row_ids",
        "required": false,
        "kind": "list"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-enrich-custom"
  },
  {
    "id": "leads.lists.columns.create",
    "method": "POST",
    "path": "/leads/lists/{list_id}/columns",
    "summary": "Add a column (static or score; code columns are copy-only)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "name",
        "required": true,
        "kind": "string"
      },
      {
        "name": "type",
        "required": true,
        "kind": "string",
        "enum": [
          "static",
          "score"
        ]
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-columns-create"
  },
  {
    "id": "leads.lists.columns.copy",
    "method": "POST",
    "path": "/leads/lists/{list_id}/columns/copy",
    "summary": "Copy a column from another list in scope (the only way to get a code column)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "source_list_id",
        "required": true,
        "kind": "string"
      },
      {
        "name": "source_column_id",
        "required": true,
        "kind": "string"
      },
      {
        "name": "name",
        "required": false,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-columns-copy"
  },
  {
    "id": "leads.lists.columns.patch",
    "method": "PATCH",
    "path": "/leads/lists/{list_id}/columns/{column_id}",
    "summary": "Patch a column's name, is_active, or relevance_weight",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "column_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "is_active",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "relevance_weight",
        "required": false,
        "kind": "string",
        "enum": [
          "very_low",
          "low",
          "medium",
          "high",
          "very_high",
          "required"
        ]
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-columns-patch"
  },
  {
    "id": "leads.lists.columns.delete",
    "method": "DELETE",
    "path": "/leads/lists/{list_id}/columns/{column_id}",
    "summary": "Delete a column (409 while other columns depend on it)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "column_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-columns-delete"
  },
  {
    "id": "leads.lists.rows.list",
    "method": "GET",
    "path": "/leads/lists/{list_id}/rows",
    "summary": "Page rows with status fields, score filter, sort, and CSV export",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "ids",
        "in": "query",
        "required": false,
        "kind": "list"
      },
      {
        "name": "min_relevance_score",
        "in": "query",
        "required": false,
        "kind": "number"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "relevance_score",
          "created_at"
        ]
      },
      {
        "name": "order",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "asc",
          "desc"
        ]
      },
      {
        "name": "include_duplicates",
        "in": "query",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "include_excluded",
        "in": "query",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "include_disapproved",
        "in": "query",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "format",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "csv"
        ]
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-rows-list"
  },
  {
    "id": "leads.lists.rows.get",
    "method": "GET",
    "path": "/leads/lists/{list_id}/rows/{row_id}",
    "summary": "Read one row (hidden rows return directly with status flags)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "row_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-rows-get"
  },
  {
    "id": "leads.lists.rows.upsert",
    "method": "POST",
    "path": "/leads/lists/{list_id}/rows/upsert",
    "summary": "Upsert rows by match columns. Sync, and embeds an enrichment job when enrich is true.",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "rows",
        "required": true,
        "kind": "json"
      },
      {
        "name": "match_columns",
        "required": true,
        "kind": "list"
      },
      {
        "name": "batch_id",
        "required": false,
        "kind": "string"
      },
      {
        "name": "enrich",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "reenrich_updated",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-rows-upsert"
  },
  {
    "id": "leads.lists.rows.delete",
    "method": "POST",
    "path": "/leads/lists/{list_id}/rows/delete",
    "summary": "Bulk-delete rows (≤1,000; all rows when omitted; previews without confirm)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "body": [
      {
        "name": "row_ids",
        "required": false,
        "kind": "list"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-rows-delete"
  },
  {
    "id": "leads.lists.rows.cells.get",
    "method": "GET",
    "path": "/leads/lists/{list_id}/rows/{row_id}/cells/{column_id}",
    "summary": "Read one cell (column id, not slug)",
    "tag": "leads",
    "params": [
      {
        "name": "list_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "row_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "column_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/leads-lists-rows-cells-get"
  },
  {
    "id": "leads.searches.get",
    "method": "GET",
    "path": "/leads/searches/{search_id}",
    "summary": "Read a search with pool depth (remaining_count, has_more, tam_known)",
    "tag": "leads",
    "params": [
      {
        "name": "search_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/leads-searches-get"
  },
  {
    "id": "leads.searches.create",
    "method": "POST",
    "path": "/leads/searches",
    "summary": "One-shot search from a brief. Creates a list, runs the search, and returns the first page.",
    "tag": "leads",
    "params": [],
    "body": [
      {
        "name": "brief",
        "required": true,
        "kind": "string"
      },
      {
        "name": "count",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "quality",
        "required": false,
        "kind": "string",
        "enum": [
          "fast",
          "accurate"
        ]
      },
      {
        "name": "exclude_list_ids",
        "required": false,
        "kind": "list"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-searches-create"
  },
  {
    "id": "leads.searches.fetch_more",
    "method": "POST",
    "path": "/leads/searches/{search_id}/fetch-more",
    "summary": "Fetch more from this search (same criteria, list, and columns)",
    "tag": "leads",
    "params": [
      {
        "name": "search_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "count",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "exclude_list_ids",
        "required": false,
        "kind": "list"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/leads-searches-fetch-more"
  },
  {
    "id": "send.campaigns.list",
    "method": "GET",
    "path": "/send/campaigns",
    "summary": "List campaigns (status and exact name filters)",
    "tag": "send",
    "params": [
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "status",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "draft",
          "active",
          "paused"
        ]
      },
      {
        "name": "name",
        "in": "query",
        "required": false,
        "kind": "string"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-list"
  },
  {
    "id": "send.campaigns.create",
    "method": "POST",
    "path": "/send/campaigns",
    "summary": "Create a blank draft campaign (no steps, people, or template required)",
    "tag": "send",
    "params": [],
    "body": [
      {
        "name": "name",
        "required": true,
        "kind": "string"
      },
      {
        "name": "channels",
        "required": true,
        "kind": "list"
      },
      {
        "name": "auto_lead_refill_enabled",
        "required": false,
        "kind": "boolean"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-create"
  },
  {
    "id": "send.campaigns.get",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}",
    "summary": "Read one campaign, including schema, template, people, and settings.",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-get"
  },
  {
    "id": "send.campaigns.delete",
    "method": "DELETE",
    "path": "/send/campaigns/{campaign_id}",
    "summary": "Delete a campaign (previews without confirm; cancels its Jobs)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-delete"
  },
  {
    "id": "send.campaigns.stats.get",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/stats",
    "summary": "Read campaign counts and rates (per-variant stats deferred)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-stats-get"
  },
  {
    "id": "send.campaigns.draft",
    "method": "POST",
    "path": "/send/campaigns/draft",
    "summary": "Fill schema and templates from a brief. Never launches.",
    "tag": "send",
    "params": [],
    "body": [
      {
        "name": "brief",
        "required": true,
        "kind": "string"
      },
      {
        "name": "channels",
        "required": false,
        "kind": "list"
      },
      {
        "name": "list_id",
        "required": false,
        "kind": "string"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-draft"
  },
  {
    "id": "send.campaigns.launch",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/launch",
    "summary": "Launch a draft (or resume a paused) campaign; dry_run reports the same gates",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "dry_run",
        "required": false,
        "kind": "boolean"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-launch"
  },
  {
    "id": "send.campaigns.pause",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/pause",
    "summary": "Pause an active campaign (idempotent)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-pause"
  },
  {
    "id": "send.campaigns.resume",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/resume",
    "summary": "Resume a paused campaign (same transition as launch on paused)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-resume"
  },
  {
    "id": "send.campaigns.settings.get",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/settings",
    "summary": "Read campaign settings",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-settings-get"
  },
  {
    "id": "send.campaigns.settings.patch",
    "method": "PATCH",
    "path": "/send/campaigns/{campaign_id}/settings",
    "summary": "Patch settings (legal in every status; omitted fields unchanged)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "channels",
        "required": false,
        "kind": "list"
      },
      {
        "name": "send_window",
        "required": false,
        "kind": "json",
        "description": "start_hour is inclusive, end_hour exclusive (0 = end of day); cross-midnight windows (start_hour > end_hour) are legal"
      },
      {
        "name": "block_active_duplicates",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "block_prior_contacts",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "auto_lead_refill_enabled",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "auto_lead_refill_budget_credits",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "require_message_approval",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "allow_excluded_recipients",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "block_already_connected",
        "required": false,
        "kind": "boolean"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-settings-patch"
  },
  {
    "id": "send.campaigns.senders.list",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/senders",
    "summary": "Read the campaign sender pool plus available org senders",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-senders-list"
  },
  {
    "id": "send.campaigns.senders.add",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/senders",
    "summary": "Add an org sender to the campaign pool",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "sender_id",
        "required": true,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-senders-add"
  },
  {
    "id": "send.campaigns.senders.remove",
    "method": "DELETE",
    "path": "/send/campaigns/{campaign_id}/senders/{sender_id}",
    "summary": "Remove a pool sender (previews affected_people without confirm)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sender_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-senders-remove"
  },
  {
    "id": "send.campaigns.people.schema.get",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/people/schema",
    "summary": "Read the campaign's People-tab columns (person_schema)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-schema-get"
  },
  {
    "id": "send.campaigns.people.schema.put",
    "method": "PUT",
    "path": "/send/campaigns/{campaign_id}/people/schema",
    "summary": "Replace the person schema. An empty fields list means identity-only.",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "fields",
        "required": true,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-schema-put"
  },
  {
    "id": "send.campaigns.people.list",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/people",
    "summary": "Page enrolled people (status filter includes bounced and unsubscribed)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "status",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "search",
        "in": "query",
        "required": false,
        "kind": "string"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-list"
  },
  {
    "id": "send.campaigns.people.upsert",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/people",
    "summary": "Enroll or update people (sync; from a list or inline; ≤1,000/call)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "list_id",
        "required": false,
        "kind": "string"
      },
      {
        "name": "row_ids",
        "required": false,
        "kind": "list"
      },
      {
        "name": "people",
        "required": false,
        "kind": "json"
      },
      {
        "name": "mapping",
        "required": false,
        "kind": "json"
      },
      {
        "name": "default_why_this_person",
        "required": false,
        "kind": "string"
      },
      {
        "name": "min_relevance_score",
        "required": false,
        "kind": "number"
      },
      {
        "name": "override_duplicate_send",
        "required": false,
        "kind": "boolean"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-upsert"
  },
  {
    "id": "send.campaigns.people.get",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}",
    "summary": "Read one person's sequence, including identity, per-step state, and sent copy.",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-get"
  },
  {
    "id": "send.campaigns.people.delete",
    "method": "DELETE",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}",
    "summary": "Delete a person (re-opens dedup; force required after sends)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "force",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-delete"
  },
  {
    "id": "send.campaigns.people.contact.patch",
    "method": "PATCH",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}/contact",
    "summary": "Patch contact info (identity pre-start only; timezone any time)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "email",
        "required": false,
        "kind": "string"
      },
      {
        "name": "linkedin_url",
        "required": false,
        "kind": "string"
      },
      {
        "name": "website_url",
        "required": false,
        "kind": "string"
      },
      {
        "name": "picture_url",
        "required": false,
        "kind": "string"
      },
      {
        "name": "timezone",
        "required": false,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-contact-patch"
  },
  {
    "id": "send.campaigns.people.steps.patch",
    "method": "PATCH",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}/steps/{step_index}",
    "summary": "Edit one person's rendered copy for a not-yet-sent step",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "step_index",
        "in": "path",
        "required": true,
        "kind": "integer"
      }
    ],
    "body": [
      {
        "name": "subject",
        "required": false,
        "kind": "string"
      },
      {
        "name": "body",
        "required": false,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-steps-patch"
  },
  {
    "id": "send.campaigns.people.remove",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}/remove",
    "summary": "Cancel a sequence; the person stays in the campaign's dedup set",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "dry_run",
        "required": false,
        "kind": "boolean"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-remove"
  },
  {
    "id": "send.campaigns.people.stop",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}/stop",
    "summary": "Stop future steps, preserving history",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "dry_run",
        "required": false,
        "kind": "boolean"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-stop"
  },
  {
    "id": "send.campaigns.people.remove_bulk",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/people/remove",
    "summary": "Bulk remove sequences (≤1,000; per-id outcomes)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "sequence_ids",
        "required": true,
        "kind": "list"
      },
      {
        "name": "dry_run",
        "required": false,
        "kind": "boolean"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-remove-bulk"
  },
  {
    "id": "send.campaigns.people.revert",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}/revert",
    "summary": "Discard person-level edits and re-render from the current template",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-revert"
  },
  {
    "id": "send.campaigns.people.sender.pin",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}/sender",
    "summary": "Pin a pool sender to one person (optionally per channel)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "sender_id",
        "required": true,
        "kind": "string"
      },
      {
        "name": "channel",
        "required": false,
        "kind": "string",
        "enum": [
          "email",
          "linkedin"
        ]
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-sender-pin"
  },
  {
    "id": "send.campaigns.people.sender.unpin",
    "method": "DELETE",
    "path": "/send/campaigns/{campaign_id}/people/{sequence_id}/sender",
    "summary": "Unpin a person's sender (optionally per channel)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "sequence_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "channel",
        "in": "query",
        "required": false,
        "kind": "string",
        "enum": [
          "email",
          "linkedin"
        ]
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-people-sender-unpin"
  },
  {
    "id": "send.campaigns.templates.get",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/templates",
    "summary": "Read the campaign template (variant_key always present on reads)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-templates-get"
  },
  {
    "id": "send.campaigns.templates.put",
    "method": "PUT",
    "path": "/send/campaigns/{campaign_id}/templates",
    "summary": "Replace the whole template (existing variant keys kept, new ones minted)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "sequences",
        "required": true,
        "kind": "json"
      },
      {
        "name": "sign_off_phrase",
        "required": false,
        "kind": "string"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-templates-put"
  },
  {
    "id": "send.campaigns.templates.clear",
    "method": "DELETE",
    "path": "/send/campaigns/{campaign_id}/templates",
    "summary": "Clear the template to an empty sequences list.",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "confirm",
        "in": "query",
        "required": false,
        "kind": "boolean"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-templates-clear"
  },
  {
    "id": "send.campaigns.templates.sequences.append",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/templates/sequences",
    "summary": "Append one template variant (fresh never-reused key)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "variant_name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "description",
        "required": false,
        "kind": "string"
      },
      {
        "name": "instructions",
        "required": false,
        "kind": "string"
      },
      {
        "name": "paused",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "steps",
        "required": true,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-templates-sequences-append"
  },
  {
    "id": "send.campaigns.templates.sequences.patch",
    "method": "PATCH",
    "path": "/send/campaigns/{campaign_id}/templates/sequences/{variant_key}",
    "summary": "Patch one variant's copy, instructions, or paused state",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "variant_key",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "variant_name",
        "required": false,
        "kind": "string"
      },
      {
        "name": "description",
        "required": false,
        "kind": "string"
      },
      {
        "name": "instructions",
        "required": false,
        "kind": "string"
      },
      {
        "name": "paused",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "steps",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-templates-sequences-patch"
  },
  {
    "id": "send.campaigns.templates.sequences.delete",
    "method": "DELETE",
    "path": "/send/campaigns/{campaign_id}/templates/sequences/{variant_key}",
    "summary": "Delete one variant (its key is never reused)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "variant_key",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-templates-sequences-delete"
  },
  {
    "id": "send.campaigns.examples.list",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/examples",
    "summary": "Page enrolled people with rendered steps",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-examples-list"
  },
  {
    "id": "send.campaigns.examples.generate",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/examples",
    "summary": "Generate per-person copy (one LLM call per person; async Job)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "overwrite_edited",
        "required": false,
        "kind": "boolean"
      },
      {
        "name": "limit",
        "required": false,
        "kind": "integer"
      },
      {
        "name": "sequence_ids",
        "required": false,
        "kind": "list"
      },
      {
        "name": "metadata",
        "required": false,
        "kind": "json"
      }
    ],
    "bodyRequired": true,
    "returnsJob": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-examples-generate"
  },
  {
    "id": "send.campaigns.approvals.list",
    "method": "GET",
    "path": "/send/campaigns/{campaign_id}/approvals",
    "summary": "Page people currently held for approval, with rendered steps",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "kind": "string"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "kind": "integer"
      }
    ],
    "paginated": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-approvals-list"
  },
  {
    "id": "send.campaigns.approvals.approve",
    "method": "POST",
    "path": "/send/campaigns/{campaign_id}/approvals/approve",
    "summary": "Release approval holds (all when sequence_ids omitted; idempotent)",
    "tag": "send",
    "params": [
      {
        "name": "campaign_id",
        "in": "path",
        "required": true,
        "kind": "string"
      }
    ],
    "body": [
      {
        "name": "sequence_ids",
        "required": false,
        "kind": "list"
      }
    ],
    "bodyRequired": true,
    "docs": "https://docs.origami.chat/v3/reference/send-campaigns-approvals-approve"
  }
];
